[CmdletBinding()]
param(
  [string]$Candidate = (Join-Path $PSScriptRoot '..\starter'),
  [string]$LocalstackEndpoint = 'http://localhost:4566',
  [switch]$UnitOnly
)
$ErrorActionPreference='Stop';Set-StrictMode -Version Latest
function Assert-Endpoint([string]$Value){
  if($Value -notmatch '^https?://(?:localhost|127\.0\.0\.1|\[::1\]):[0-9]{1,5}$'){throw "Unsafe endpoint: $Value"}
  try{$u=[Uri]$Value}catch{throw "Invalid endpoint: $Value"}
  if(-not $u.IsAbsoluteUri -or $u.DnsSafeHost -notin @('localhost','127.0.0.1','::1') -or $u.UserInfo -ne '' -or $u.AbsolutePath -ne '/' -or $u.Query -ne '' -or $u.Fragment -ne '' -or $u.Port -lt 1 -or $u.Port -gt 65535){throw "Unsafe endpoint: $Value"}
}
function Native([string]$File,[string[]]$Arguments,[int[]]$Allowed=@(0),[switch]$Quiet){
  $old=$ErrorActionPreference;$ErrorActionPreference='Continue';$lines=@(&$File @Arguments 2>&1);$code=$LASTEXITCODE;$ErrorActionPreference=$old;$text=$lines -join "`n"
  if(-not $Quiet -and $lines.Count){$lines|Out-Host};if($code -notin $Allowed){throw "$File failed ($code): $($Arguments -join ' ')`n$text"};[pscustomobject]@{Code=$code;Text=$text}
}
function Tf([string]$Dir,[string[]]$Arguments,[int[]]$Allowed=@(0),[switch]$Quiet){Native 'terraform' (@("-chdir=$Dir")+$Arguments) $Allowed -Quiet:$Quiet}
function Aws([string[]]$Arguments,[int[]]$Allowed=@(0),[switch]$Quiet){Native 'aws.exe' (@('--endpoint-url',$LocalstackEndpoint,'--region','us-east-1')+$Arguments) $Allowed -Quiet:$Quiet}
function Copy-Clean([string]$Source,[string]$Destination){New-Item -ItemType Directory -Force $Destination|Out-Null;foreach($i in Get-ChildItem -LiteralPath $Source -Force){if($i.Name -in @('.terraform','.terraform.lock.hcl','terraform.tfstate','terraform.tfstate.backup') -or $i.Extension -in @('.tfplan','.tfstate')){continue};Copy-Item -LiteralPath $i.FullName -Destination $Destination -Recurse -Force}}
function Exact-Tests([string]$Dir,[int]$Expected){$r=Tf $Dir @('test','-test-directory=tests','-no-color');if([regex]::Matches($r.Text,"(?m)^Success!\s+$Expected passed,\s+0 failed\.\s*$").Count -ne 1 -or [regex]::Matches($r.Text,'(?m)^\s*run\s+"[^"]+"\.\.\.\s+pass\s*$').Count -ne $Expected){throw "Expected $Expected exact test runs."}}
Assert-Endpoint $LocalstackEndpoint
$candidatePath=(Resolve-Path -LiteralPath $Candidate).Path;$files=@(Get-ChildItem -LiteralPath $candidatePath -Recurse -File)
if($files.Count -eq 0 -or @($files|Where-Object Extension -ne '.tf').Count){throw 'Candidate must contain Terraform HCL only.'}
$text=($files|ForEach-Object{Get-Content -Raw -LiteralPath $_.FullName}) -join "`n"
if($text -match '(?i)\b(mock_provider|override_data|override_resource|profile|shared_credentials_files|assume_role|aws_vpc|aws_subnet"\s+"[^s])\b|AKIA[0-9A-Z]{16}'){throw 'Forbidden mock, credential, or managed-network mechanism found.'}
$resources=@([regex]::Matches($text,'resource\s+"(aws_[a-z0-9_]+)"')|ForEach-Object{$_.Groups[1].Value}|Sort-Object -Unique);$data=@([regex]::Matches($text,'data\s+"(aws_[a-z0-9_]+)"')|ForEach-Object{$_.Groups[1].Value}|Sort-Object -Unique)
if(($resources -join ',') -ne 'aws_instance,aws_launch_template,aws_security_group'){throw "Unexpected AWS resources: $($resources -join ',')"};if(($data -join ',') -ne 'aws_ami,aws_subnet'){throw "Unexpected AWS data sources: $($data -join ',')"}
if([regex]::Matches($text,'for_each\s*=\s*local\.fleets_by_id').Count -ne 3 -or $text -notmatch 'output\s+"catalog_guard"[\s\S]*?precondition' -or $text -match 'desired_capacity|min_size|max_size|terraform_data|ignore_changes'){throw 'Stable fleet graph or blocking catalog guard is incomplete.'}
if($text -notmatch 'LaunchTemplateId\s*=\s*aws_launch_template\.fleet\[each\.key\]\.id'){throw 'Instance audit tags must reference the real launch-template ID.'}
if($text -notmatch 'access_key\s*=\s*"test"' -or $text -notmatch 'secret_key\s*=\s*"test"' -or $text -notmatch 'skip_credentials_validation\s*=\s*true' -or $text -notmatch 'skip_metadata_api_check\s*=\s*true' -or $text -notmatch 'skip_requesting_account_id\s*=\s*true'){throw 'Safe provider contract missing.'}
$runId=([Guid]::NewGuid().ToString('N')).Substring(0,10);$temp=Join-Path ([IO.Path]::GetTempPath()) "tfpro-c31-$runId";$work=Join-Path $temp 'candidate';$vpcId=$null;$subnets=@();$failure=$null
$oldA=$env:AWS_ACCESS_KEY_ID;$oldS=$env:AWS_SECRET_ACCESS_KEY;$oldR=$env:AWS_DEFAULT_REGION;$oldN=$env:TF_VAR_subnet_ids;$env:AWS_ACCESS_KEY_ID='test';$env:AWS_SECRET_ACCESS_KEY='test';$env:AWS_DEFAULT_REGION='us-east-1'
try{
  try{Invoke-WebRequest -UseBasicParsing -Uri "$($LocalstackEndpoint.TrimEnd('/'))/_localstack/health" -TimeoutSec 5|Out-Null}catch{throw 'LocalStack unavailable.'}
  $vpcId=(Aws @('ec2','create-vpc','--cidr-block','10.131.0.0/16','--tag-specifications',"ResourceType=vpc,Tags=[{Key=RunId,Value=$runId}]",'--query','Vpc.VpcId','--output','text') -Quiet).Text.Trim()
  $public=(Aws @('ec2','create-subnet','--vpc-id',$vpcId,'--cidr-block','10.131.1.0/24','--availability-zone','us-east-1a','--tag-specifications',"ResourceType=subnet,Tags=[{Key=RunId,Value=$runId}]",'--query','Subnet.SubnetId','--output','text') -Quiet).Text.Trim();$subnets+=$public
  $private=(Aws @('ec2','create-subnet','--vpc-id',$vpcId,'--cidr-block','10.131.2.0/24','--availability-zone','us-east-1b','--tag-specifications',"ResourceType=subnet,Tags=[{Key=RunId,Value=$runId}]",'--query','Subnet.SubnetId','--output','text') -Quiet).Text.Trim();$subnets+=$private
  $env:TF_VAR_subnet_ids=(@{'public-a'=$public;'private-a'=$private}|ConvertTo-Json -Compress)
  Copy-Clean $candidatePath $work;Copy-Item -LiteralPath (Join-Path $PSScriptRoot '..\fixtures') -Destination (Join-Path $temp 'fixtures') -Recurse -Force;New-Item -ItemType Directory -Force (Join-Path $work 'tests')|Out-Null;Copy-Item (Join-Path $PSScriptRoot 'canonical.tftest.hcl') (Join-Path $work 'tests\canonical.tftest.hcl')
  Tf $work @('fmt','-check','-recursive')|Out-Null;Tf $work @('init','-backend=false','-input=false','-no-color')|Out-Null;Tf $work @('validate','-no-color')|Out-Null;Exact-Tests $work 10
  if($UnitOnly){Write-Host 'PASS: Challenge 31 exact 10/10 TF1.6 tests with real AMI/subnet data.';return}
  Remove-Item (Join-Path $work 'tests') -Recurse -Force;$common=@('-input=false','-no-color',"-var=run_id=$runId",'-var=name_prefix=tfpro-c31','-var=environment=prod','-var=fleet_csv_path=../fixtures/fleets.csv')
  $plan=Join-Path $work 'reviewed.tfplan';Tf $work (@('plan',"-out=$plan")+$common)|Out-Null;$json=(Tf $work @('show','-json',$plan) -Quiet).Text|ConvertFrom-Json;$creates=@($json.resource_changes|Where-Object{(@($_.change.actions)-join ',') -eq 'create'});if($creates.Count -ne 6){throw "Expected exactly six creates, got $($creates.Count)."}
  Tf $work @('apply','-input=false','-no-color',$plan)|Out-Null;$contract=(Tf $work @('output','-json','fleet_contract') -Quiet).Text|ConvertFrom-Json
  foreach($id in @('api','worker')){$f=$contract.fleets.$id;if($f.subnet_id -notin $subnets -or $f.vpc_id -ne $vpcId){throw "$id network contract mismatch."};$instance=(Aws @('ec2','describe-instances','--instance-ids',$f.instance_id,'--query','Reservations[0].Instances[0]','--output','json') -Quiet).Text|ConvertFrom-Json;$tags=@{};foreach($tag in $instance.Tags){$tags[$tag.Key]=$tag.Value};if($tags.RunId -ne $runId -or $tags.FleetId -ne $id -or $tags.LaunchTemplateId -ne $f.launch_template_id){throw "$id instance tags mismatch."};$lt=(Aws @('ec2','describe-launch-template-versions','--launch-template-id',$f.launch_template_id,'--versions','$Latest','--query','LaunchTemplateVersions[0].LaunchTemplateData','--output','json') -Quiet).Text|ConvertFrom-Json;if($lt.ImageId -ne $contract.ami_id -or $lt.InstanceType -ne $f.instance_type){throw "$id launch-template data mismatch."}}
  $reorder=Tf $work (@('plan','-detailed-exitcode')+($common|Where-Object{$_ -notlike '-var=fleet_csv_path=*'})+@('-var=fleet_csv_path=../fixtures/fleets-reordered.csv')) @(0,2) -Quiet;if($reorder.Code -ne 0){throw "CSV reorder changed the graph.`n$($reorder.Text)"}
  $victim=$contract.fleets.api.instance_id;Aws @('ec2','create-tags','--resources',$victim,'--tags','Key=Name,Value=tampered')|Out-Null;$drift=Join-Path $work 'drift.tfplan';$dr=Tf $work (@('plan','-detailed-exitcode',"-out=$drift")+$common) @(0,2) -Quiet;if($dr.Code -ne 2){throw 'Instance tag drift not detected.'};$dj=(Tf $work @('show','-json',$drift) -Quiet).Text|ConvertFrom-Json;$updates=@($dj.resource_changes|Where-Object{$_.address -eq 'aws_instance.fleet["api"]' -and (@($_.change.actions)-join ',') -eq 'update'});if($updates.Count -ne 1){throw 'Drift plan must update only api instance.'};Tf $work @('apply','-input=false','-no-color',$drift)|Out-Null
  $clean=Tf $work (@('plan','-detailed-exitcode')+$common) @(0,2) -Quiet;if($clean.Code -ne 0){throw 'Post-repair plan not clean.'};Tf $work (@('destroy','-auto-approve')+$common)|Out-Null
  $ltNames=(Aws @('ec2','describe-launch-templates','--query','LaunchTemplates[].LaunchTemplateName','--output','text') -Quiet).Text;$sgs=(Aws @('ec2','describe-security-groups','--filters',"Name=tag:RunId,Values=$runId",'--query','SecurityGroups[].GroupId','--output','text') -Quiet).Text;$active=(Aws @('ec2','describe-instances','--filters',"Name=tag:RunId,Values=$runId",'Name=instance-state-name,Values=pending,running,stopping,stopped','--query','Reservations[].Instances[].InstanceId','--output','text') -Quiet).Text;if($ltNames -match "tfpro-c31-(api|worker)-$runId" -or -not [string]::IsNullOrWhiteSpace($sgs) -or -not [string]::IsNullOrWhiteSpace($active)){throw 'Managed EC2 residue remains.'}
  Write-Host 'PASS: Challenge 31 TF1.6 tests + official EC2 graph + saved plan/reorder/drift repair + zero managed residue.'
}catch{$failure=$_}finally{$old=$ErrorActionPreference;$ErrorActionPreference='Continue';if(Test-Path $work){&terraform "-chdir=$work" destroy -auto-approve -input=false -no-color "-var=run_id=$runId" '-var=name_prefix=tfpro-c31' '-var=environment=prod' '-var=fleet_csv_path=../fixtures/fleets.csv' 2>$null|Out-Null};foreach($s in $subnets){&aws.exe --endpoint-url $LocalstackEndpoint --region us-east-1 ec2 delete-subnet --subnet-id $s 2>$null|Out-Null};if($vpcId){&aws.exe --endpoint-url $LocalstackEndpoint --region us-east-1 ec2 delete-vpc --vpc-id $vpcId 2>$null|Out-Null};$env:AWS_ACCESS_KEY_ID=$oldA;$env:AWS_SECRET_ACCESS_KEY=$oldS;$env:AWS_DEFAULT_REGION=$oldR;$env:TF_VAR_subnet_ids=$oldN;if(Test-Path $temp){Remove-Item $temp -Recurse -Force};$ErrorActionPreference=$old};if($failure){throw $failure}
